/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------*/
/**        \file  Port_PBcfg.c
 *        \brief  Post Build Configuration Source file for Port Module.
 *
 *      \details   
 *
 *
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "Port.h"

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration =
{
		{ {PORTA_NUM, PIN0, PORT_PIN_IN, PORT_PIN_MODE_UART, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
     	{PORTA_NUM, PIN1, PORT_PIN_IN, PORT_PIN_MODE_UART, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN1, PORT_PIN_IN, PORT_PIN_MODE_SSI, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN2, PORT_PIN_IN, PORT_PIN_MODE_SSI, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN3, PORT_PIN_IN, PORT_PIN_MODE_SSI, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN4, PORT_PIN_IN, PORT_PIN_MODE_SSI, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN5, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN6, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},

	    {PORTB_NUM, PIN0, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN1, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN2, PORT_PIN_IN, PORT_PIN_MODE_I2C, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN3, PORT_PIN_IN, PORT_PIN_MODE_I2C, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN4, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN5, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN6, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN7, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},

		  {PORTC_NUM, PIN0, PORT_PIN_IN, PORT_PIN_MODE_JTAG, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN1, PORT_PIN_IN, PORT_PIN_MODE_JTAG, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN2, PORT_PIN_IN, PORT_PIN_MODE_JTAG, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN3, PORT_PIN_IN, PORT_PIN_MODE_JTAG, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN4, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN5, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN6, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN7, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},

		  {PORTD_NUM, PIN0, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN1, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN2, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN3, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN4, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN5, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN6, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN7, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
              
      {PORTE_NUM, PIN0, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN1, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN2, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN3, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN4, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN5, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		              
      {PORTF_NUM, PIN0, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTF_NUM, PIN1, PORT_PIN_OUT, PORT_PIN_MODE_DIO, NOT_APPLICABLE, PORT_PIN_LEVEL_LOW, PORT_PIN_OUTPUT_CURRENT_2m},
		  {PORTF_NUM, PIN2, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTF_NUM, PIN3, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE},
		  {PORTF_NUM, PIN4, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE, NOT_APPLICABLE}}
                

};


/**********************************************************************************************************************
 *  END OF FILE: Port_PBcfg.c
 *********************************************************************************************************************/
